export const PLAYLIST_TRENDING_REQUESTED = 'PLAYLIST_TRENDING_REQUESTED';
export const PLAYLIST_TRENDING_ERROR = 'PLAYLIST_TRENDING_ERROR';
export const PLAYLIST_TRENDING_SUCCESS = 'PLAYLIST_TRENDING_SUCCESS';

export const ADD_EXPIRATIO_DATE = 'ADD_EXPIRATIO_DATE';

export const NEW_RELEASE_REQUESTED = 'NEW_RELEASE_REQUESTED';
export const NEW_RELEASE_ERROR = 'NEW_RELEASE_ERROR';
export const NEW_RELEASE_SUCCESS = 'NEW_RELEASE_SUCCESS';

export const CLOSE_MODAL_DETAILS = 'CLOSE_MODAL_DETAILS';
export const OPEN_MODAL_DETAILS = 'OPEN_MODAL_DETAILS';

export const PLAYLIST_TRACKS_REQUESTED = 'PLAYLIST_TRACKS_REQUESTED';
export const PLAYLIST_TRACKS_ERROR = 'PLAYLIST_TRACKS_ERROR';
export const PLAYLIST_TRACKS_SUCCESS = 'PLAYLIST_TRACKS_SUCCESS';

export const GET_SEARCH_TRACKS_SUCCESS = 'GET_SEARCH_TRACKS_SUCCESS';
export const GET_SEARCH_TRACKS_REQUESTED = 'GET_SEARCH_TRACKS_REQUESTED';
export const GET_SEARCH_TRACKS_ERROR = 'GET_SEARCH_TRACKS_ERROR';

export const GET_CATEGORIES_SUCCESS = 'GET_FILTERED_PLAYLIST_SUCCESS';
export const GET_CATEGORIES_REQUESTED = 'GET_CATEGORIES_REQUESTED';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const GET_CATEGORY_PLAYLIST_SUCCESS = 'GET_CATEGORY_PLAYLIST_SUCCESS';
export const GET_CATEGORY_PLAYLIST_REQUESTED = 'GET_CATEGORY_PLAYLIST_REQUESTED';
export const GET_CATEGORY_PLAYLIST_ERROR = 'GET_CATEGORY_PLAYLIST_ERROR';


export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';

export const GET_MOCKY_FILTERS_SUCCESS = 'GET_MOCKY_FILTERS_SUCCESS';
export const GET_MOCKY_FILTERS_REQUESTED = 'GET_MOCKY_FILTERS_REQUESTED';
export const GET_MOCKY_FILTERS_ERROR = 'GET_MOCKY_FILTERS_ERROR';